version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build_and_test:
    docker:
      - image: <obraz_pythona>
        environment:
          ..... 
      - image: <obraz_postgresa>
        environment:          
          POSTGRES_USER: <POSTGRES_USER>
          POSTGRES_DB: <POSTGRES_DB>
    steps:
      - checkout
      ....
      ....
      ....
      ....

workflows:
  on_commit:
    jobs:
      - build_and_test
